"""phase3: contacts, contact_inboxes, notes, custom_attribute_definitions

Revision ID: b6166907e906
Revises: b2c3d4e5f6a7
Create Date: 2026-04-20 11:50:58.457012
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'b6166907e906'
down_revision: str | Sequence[str] | None = 'b2c3d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), server_default='', nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), server_default='', nullable=True),
    sa.Column('last_name', sa.String(), server_default='', nullable=True),
    sa.Column('location', sa.String(), server_default='', nullable=True),
    sa.Column('country_code', sa.String(), server_default='', nullable=True),
    sa.Column('blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('contact_type', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('additional_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'account_id', name='uniq_email_per_account_contact'),
    sa.UniqueConstraint('identifier', 'account_id', name='uniq_identifier_per_account_contact')
    )
    op.create_index('index_contacts_on_account_id', 'contacts', ['account_id'], unique=False)
    op.create_index('index_contacts_on_account_id_and_contact_type', 'contacts', ['account_id', 'contact_type'], unique=False)
    op.create_index('index_contacts_on_account_id_and_last_activity_at', 'contacts', ['account_id', 'last_activity_at'], unique=False)
    op.create_index('index_contacts_on_blocked', 'contacts', ['blocked'], unique=False)
    op.create_index('index_contacts_on_company_id', 'contacts', ['company_id'], unique=False)
    op.create_index('index_contacts_on_lower_email_account_id', 'contacts', [sa.literal_column('lower(email)'), 'account_id'], unique=False)
    op.create_index('index_contacts_on_phone_number_and_account_id', 'contacts', ['phone_number', 'account_id'], unique=False)
    op.create_table('custom_attribute_definitions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('attribute_display_name', sa.String(), nullable=True),
    sa.Column('attribute_key', sa.String(), nullable=True),
    sa.Column('attribute_description', sa.Text(), nullable=True),
    sa.Column('attribute_display_type', sa.Integer(), server_default='0', nullable=True),
    sa.Column('attribute_model', sa.Integer(), server_default='0', nullable=True),
    sa.Column('attribute_values', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('default_value', sa.Integer(), nullable=True),
    sa.Column('regex_pattern', sa.String(), nullable=True),
    sa.Column('regex_cue', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_key', 'attribute_model', 'account_id', name='attribute_key_model_index')
    )
    op.create_index('index_custom_attribute_definitions_on_account_id', 'custom_attribute_definitions', ['account_id'], unique=False)
    op.create_table('contact_inboxes',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('inbox_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('pubsub_token', sa.String(), nullable=True),
    sa.Column('hmac_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_contact_inboxes_on_contact_id', 'contact_inboxes', ['contact_id'], unique=False)
    op.create_index('index_contact_inboxes_on_inbox_id', 'contact_inboxes', ['inbox_id'], unique=False)
    op.create_index('index_contact_inboxes_on_inbox_id_and_source_id', 'contact_inboxes', ['inbox_id', 'source_id'], unique=True)
    op.create_index('index_contact_inboxes_on_pubsub_token', 'contact_inboxes', ['pubsub_token'], unique=True)
    op.create_index('index_contact_inboxes_on_source_id', 'contact_inboxes', ['source_id'], unique=False)
    op.create_table('notes',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_notes_on_account_id', 'notes', ['account_id'], unique=False)
    op.create_index('index_notes_on_contact_id', 'notes', ['contact_id'], unique=False)
    op.create_index('index_notes_on_user_id', 'notes', ['user_id'], unique=False)
    op.alter_column('inbox_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('inbox_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inbox_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inbox_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('index_notes_on_user_id', table_name='notes')
    op.drop_index('index_notes_on_contact_id', table_name='notes')
    op.drop_index('index_notes_on_account_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index('index_contact_inboxes_on_source_id', table_name='contact_inboxes')
    op.drop_index('index_contact_inboxes_on_pubsub_token', table_name='contact_inboxes')
    op.drop_index('index_contact_inboxes_on_inbox_id_and_source_id', table_name='contact_inboxes')
    op.drop_index('index_contact_inboxes_on_inbox_id', table_name='contact_inboxes')
    op.drop_index('index_contact_inboxes_on_contact_id', table_name='contact_inboxes')
    op.drop_table('contact_inboxes')
    op.drop_index('index_custom_attribute_definitions_on_account_id', table_name='custom_attribute_definitions')
    op.drop_table('custom_attribute_definitions')
    op.drop_index('index_contacts_on_phone_number_and_account_id', table_name='contacts')
    op.drop_index('index_contacts_on_lower_email_account_id', table_name='contacts')
    op.drop_index('index_contacts_on_company_id', table_name='contacts')
    op.drop_index('index_contacts_on_blocked', table_name='contacts')
    op.drop_index('index_contacts_on_account_id_and_last_activity_at', table_name='contacts')
    op.drop_index('index_contacts_on_account_id_and_contact_type', table_name='contacts')
    op.drop_index('index_contacts_on_account_id', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
