"""phase1_accounts_users_account_users_access_tokens

Revision ID: eb5b562ecc47
Revises: 
Create Date: 2026-04-17 23:39:51.309812
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'eb5b562ecc47'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_tokens_token'), 'access_tokens', ['token'], unique=True)
    op.create_table('accounts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('locale', sa.Integer(), server_default='0', nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('support_email', sa.String(length=100), nullable=True),
    sa.Column('feature_flags', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('auto_resolve_duration', sa.Integer(), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('internal_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), server_default='email', nullable=False),
    sa.Column('uid', sa.String(), server_default='', nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('encrypted_password', sa.String(), server_default='', nullable=False),
    sa.Column('reset_password_token', sa.String(), nullable=True),
    sa.Column('reset_password_sent_at', sa.DateTime(), nullable=True),
    sa.Column('remember_created_at', sa.DateTime(), nullable=True),
    sa.Column('sign_in_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('current_sign_in_ip', sa.String(), nullable=True),
    sa.Column('last_sign_in_ip', sa.String(), nullable=True),
    sa.Column('confirmation_token', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('unconfirmed_email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('message_signature', sa.Text(), nullable=True),
    sa.Column('tokens', sa.JSON(), nullable=True),
    sa.Column('pubsub_token', sa.String(), nullable=True),
    sa.Column('availability', sa.Integer(), server_default='0', nullable=True),
    sa.Column('ui_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('otp_secret', sa.String(), nullable=True),
    sa.Column('consumed_timestep', sa.Integer(), nullable=True),
    sa.Column('otp_required_for_login', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('otp_backup_codes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otp_secret'),
    sa.UniqueConstraint('pubsub_token'),
    sa.UniqueConstraint('reset_password_token'),
    sa.UniqueConstraint('uid', 'provider', name='index_users_on_uid_and_provider')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_otp_required_for_login'), 'users', ['otp_required_for_login'], unique=False)
    op.create_table('account_users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Integer(), server_default='0', nullable=True),
    sa.Column('inviter_id', sa.BigInteger(), nullable=True),
    sa.Column('active_at', sa.DateTime(), nullable=True),
    sa.Column('availability', sa.Integer(), server_default='0', nullable=False),
    sa.Column('auto_offline', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('custom_role_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_capacity_policy_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'user_id', name='uniq_user_id_per_account_id')
    )
    op.create_index(op.f('ix_account_users_account_id'), 'account_users', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_users_agent_capacity_policy_id'), 'account_users', ['agent_capacity_policy_id'], unique=False)
    op.create_index(op.f('ix_account_users_custom_role_id'), 'account_users', ['custom_role_id'], unique=False)
    op.create_index(op.f('ix_account_users_user_id'), 'account_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_users_user_id'), table_name='account_users')
    op.drop_index(op.f('ix_account_users_custom_role_id'), table_name='account_users')
    op.drop_index(op.f('ix_account_users_agent_capacity_policy_id'), table_name='account_users')
    op.drop_index(op.f('ix_account_users_account_id'), table_name='account_users')
    op.drop_table('account_users')
    op.drop_index(op.f('ix_users_otp_required_for_login'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_access_tokens_token'), table_name='access_tokens')
    op.drop_table('access_tokens')
    # ### end Alembic commands ###
